const { initDatabase, saveDb } = require('./init');

async function seedDatabase() {
  const db = await initDatabase();

  // Clear existing data
  db.run('DELETE FROM submission');
  db.run('DELETE FROM payment');
  db.run('DELETE FROM event_coordinator');
  db.run('DELETE FROM faculty_coordinator');
  db.run('DELETE FROM registration');
  db.run('DELETE FROM team_members');
  db.run('DELETE FROM team');
  db.run('DELETE FROM student');
  db.run('DELETE FROM event');
  db.run('DELETE FROM event_category');

  // Seed categories
  const categories = ['Cultural Events', 'Technical Events', 'Sport Events', 'Fun & Adventure Events'];
  categories.forEach(c => db.run('INSERT INTO event_category (category_name) VALUES (?)', [c]));

  // Seed events
  const insertSQL = `INSERT INTO event (event_name, category_id, competition_type, description, rules, min_participants, max_participants, date, venue, fee, fee_label, prize_pool, coordinator_name, coordinator_phone, image_icon) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`;

  const events = [
    // ====== CULTURAL EVENTS (category_id = 1) ======
    ["Virasat: The Folk Dance Showcase", 1, "Group", "Celebrate the vibrant tapestry of our cultural heritage at Virasat! This group folk dance competition is a stage for tradition, energy, and rhythm. Whether your team is bringing the fierce, captivating energy of Chhau, the rhythmic beats of Jhumar, or any other traditional dance form from across the nation, we want to see your roots on display. Bring your authentic costumes, your best choreography, and let the culture take center stage.", "1. Group Size: Each team must consist of a minimum of 4 and a maximum of 12 participants.\n2. Time Limit: Performances must be between 4 to 6 minutes long. The timer begins as soon as the music starts or the first movement is made on stage.\n3. Music: High-quality audio tracks must be uploaded during registration. Teams are advised to carry a backup of their track on a USB drive on the day of the event.\n4. Props: Traditional props relevant to the dance form are encouraged. However, the use of fire, glass, liquid, or any hazardous material is strictly prohibited and will lead to immediate disqualification.\n5. Decorum: Costumes and dance moves must maintain the cultural authenticity and dignity of the folk form.", 4, 12, "April 16-17", "Main Stage, CIT Ranchi", 0, "FREE", "A Celebration, Not a Competition. Folk dance is a reflection of culture, and every culture is beyond comparison. No judging, just pure celebration! Free Entry + Certificates, Merch, and Snacks for all performers.", "Shruti Jaiswal", "8210600034", "💃"],
    ["Tune and Triumph (Singing)", 1, "Solo", "Is your voice ready to rule the stage? \"Tune and Triumph\" is the ultimate solo singing battle at Genesis. Whether you are a classically trained vocalist, a pop powerhouse, or an indie soul with an acoustic guitar, this is your moment to shine. Grab the mic, hit the right notes, and let your voice leave the audience spellbound.", "1. Format: Solo performance only. Participants can sing acapella, play one acoustic/electric instrument while singing, or sing over a pre-recorded karaoke track.\n2. Time Limit: Performances must not exceed 4 minutes.\n3. Karaoke Tracks: If using a backing track, it must be instrumental only (no pre-recorded lead vocals allowed).\n4. Language & Content: Songs can be in any Indian language or English. Lyrics must be strictly clean.\n5. Equipment: Organizers will provide standard microphones and DI boxes for instruments. Participants must bring their own instruments and necessary cables.", 1, 1, "April 16-17", "Main Stage, CIT Ranchi", 500, "₹500", "1st Prize: ₹5,000 | 2nd Prize: ₹3,000 | All participants receive Certificates of Participation, exclusive event merch!", "Komal Gupta", "8582073552", "🎤"],
    ["Art in Motion (Dance)", 1, "Solo/Group", "The stage is yours, and the spotlight is waiting. \"Art in Motion\" is the ultimate dance battle at Genesis, where technique meets pure expression. Whether you flow with contemporary grace, hit hard with hip-hop, or dazzle with Bollywood energy, we want to see your story unfold through movement.", "1. Format: Solo or Group. All dance styles are welcome.\n2. Time Limit: Performances must be between 2 to 4 minutes long.\n3. Music: High-quality audio tracks must be uploaded in MP3/WAV format during registration.\n4. Props: Safe props are allowed with prior declaration. The use of fire, glass, liquids, or any hazardous material is strictly prohibited.\n5. Decorum: Costumes and choreography must be appropriate for a college fest audience.", 1, 12, "April 16-17", "Main Stage, CIT Ranchi", 500, "₹500", "Solo: 1st Prize ₹5,000 / 2nd Prize ₹3,000 | Group: 1st Prize ₹7,000 / 2nd Prize ₹4,000 | All participants receive Certificates!", "Praveen", "6200403654", "🕺"],
    ["Canvas of Expressions (Face Painting)", 1, "Solo", "Unleash your imagination and turn the human face into a walking masterpiece! \"Canvas of Expressions\" is Genesis's premier face painting competition. Bring your artistic vision to life and let your creativity speak for itself!", "1. Format: Solo competition. The participant may bring one model or paint their own face.\n2. Theme: Open – full creative freedom.\n3. Time Limit: Exactly 60 minutes.\n4. Materials: Participants MUST bring their own skin-safe, non-toxic face paints. Poster colors or acrylics will lead to disqualification.\n5. Aids: No stencils, stamps, or temporary tattoos. Freehand only.\n6. Coverage: Painting must cover at least 70% of the face.", 1, 1, "April 16-17", "Art Zone, CIT Ranchi", 300, "₹300", "1st Prize: ₹3,000 | 2nd Prize: ₹2,000 | All participants receive Certificates!", "Kundan Kumar", "7903946288", "🎨"],
    ["Runway Royal (Ramp Walk)", 1, "Solo/Group", "The spotlight is yours. Own it. \"The Royal Runway\" is Genesis's premier fashion event. We are looking for unapologetic style, fierce walks, and absolute stage presence. Strut your stuff, hit your poses, and leave the crowd breathless!", "1. Format: Solo or Group competition.\n2. Time Limit: Each participant gets 60-90 seconds on stage.\n3. Audio: Participants MUST upload their background track during registration.\n4. Theme: Bollywood Glam – all outfits must maintain decency appropriate for a college environment.\n5. Props: Safe handheld props allowed. Fire, glass, animals are prohibited.\n6. Backstage: Report 30 minutes before the event begins.", 1, 10, "April 16-17", "Main Stage, CIT Ranchi", 300, "Solo: ₹300 | Group: ₹1,000", "Solo: ₹3,000 (1 Male & 1 Female) | Group: ₹10,000 | Certificates for all!", "Shweta Sahu", "7091693590", "👗"],
    ["Comic Monologue (Stand-Up Comedy)", 1, "Solo", "Think you have what it takes to leave a room in splits? \"Comic Monologue\" is your chance to grab the mic and own the Genesis stage with your best jokes and perfect comedic timing!", "1. Format: Solo stand-up comedy performance.\n2. Time Limit: 3 to 5 minutes on stage.\n3. Language: English, Hindi, or a mix.\n4. Content: No hate speech, personal attacks, or NSFW content.\n5. Originality: Plagiarized jokes will be scored poorly.", 1, 1, "April 16-17", "Main Stage, CIT Ranchi", 300, "₹300", "1st Prize: ₹3,000 | 2nd Prize: ₹2,000 | Certificates for all!", "Lakshmi Narayan", "8252263380", "🎭"],
    ["Awaaz (Nukkad Natak)", 1, "Group", "Gather around and feel the energy! \"Awaaz\" is Genesis's flagship Nukkad Natak competition. Use your art to spark conversations, challenge societal norms, and deliver a hard-hitting social message!", "1. Team Size: 8 to 20 participants.\n2. Time Limit: 10 to 15 minutes including setup and clearance.\n3. Language: Primarily Hindi or English.\n4. Audio: Pre-recorded background tracks and live instruments are encouraged.\n5. Props: Standard safe street play props only. No throwing colors or liquids.\n6. Content: Must focus on a social message. No derogatory attacks.", 8, 20, "April 16-17", "Campus Circle, CIT Ranchi", 800, "₹800", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Shivam", "8120441749", "🎪"],
    ["Crescendo (Band Competition)", 1, "Group", "Turn up the amps and let the distortion roar! \"Crescendo\" is the ultimate Battle of the Bands at Genesis. Bring your tightest riffs, your heaviest basslines, and your most electrifying stage presence!", "1. Band Size: 3 to 8 members.\n2. Time Limit: Exactly 20 minutes including soundcheck, setup, performance, and clearance.\n3. Equipment Provided: 5-piece drum kit, guitar/bass amps, vocal mics, DI boxes.\n4. Bring Your Own: Guitars, keyboards, drumsticks, effects pedals, cables.\n5. Repertoire: Covers or originals (bonus for originals).\n6. Decorum: No profanity, no smashing instruments.", 3, 8, "April 16-17", "Main Stage, CIT Ranchi", 3000, "₹3,000", "1st Prize: ₹25,000 | 2nd Prize: ₹10,000 | Certificates for all!", "Tanay Oran", "9102947947", "🎸"],

    // ====== TECHNICAL EVENTS (category_id = 2) ======
    ["Circuit Designing", 2, "Group", "Test your electrical wits and hardware mastery! Circuit Designing is a two-stage technical showdown where theoretical knowledge meets practical execution.", "1. Format: Group competition, 3-hour time limit.\n2. Materials: Each group must bring their own working model and materials.\n3. Power Supply: 220V AC provided; bring your own extension cords.\n4. No modifications allowed once the clock begins.\n5. Safety: Adhere to laboratory safety norms.\n6. Punctuality: Arrive 30 minutes before scheduled time.", 2, 5, "April 16", "Lab Block, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Aryan", "7294027767", "⚡"],
    ["HackGenesis: The 24-Hour Codefest", 2, "Solo/Team", "Sleep is a myth; code is reality. Welcome to \"HackGenesis,\" a grueling, exhilarating 24-hour hackathon where your ideas turn into execution!", "1. Team Size: Solo or up to 4 members.\n2. Duration: Exactly 24 hours.\n3. Bring your own laptops and chargers.\n4. We provide: Wi-Fi, power sockets, unlimited snacks/cold drinks.\n5. Code Originality: All code must be written during the hackathon.\n6. Code of Conduct: No malicious network activity.", 1, 4, "April 16-17", "CS Lab, CIT Ranchi", 1500, "₹1,500", "1st Prize: ₹20,000 | 2nd Prize: ₹10,000 | Unlimited snacks & Certificates!", "Arkaprava", "8918602092", "💻"],
    ["Syntax Sniper: The Debugging Challenge", 2, "Solo", "Anyone can write code, but it takes a true master to fix it when it breaks. Find the bug, fix the code, and make it run!", "1. Format: Solo competition.\n2. College computer labs only – no personal laptops.\n3. 10 broken code snippets of varying difficulty.\n4. Time Limit: 60 minutes.\n5. NO Internet, NO AI tools, NO external resources.", 1, 1, "April 16-17", "CS Lab, CIT Ranchi", 500, "₹500", "1st Prize: ₹5,000 | 2nd Prize: ₹3,000 | Certificates for all!", "Arpita Sinha", "9199691596", "🐛"],
    ["Truss It to Win It", 2, "Group", "Put your structural engineering skills to the ultimate test! Design and construct a lightweight, hydraulic bridge model using simple everyday materials.", "1. Team Size: Up to 5 members.\n2. Materials: Ice cream sticks, Fevicol, Syringes, Plastic tubing/IV Pipe only.\n3. Bridge will be tested for load-bearing capacity.\n4. Hydraulic mechanism must be demonstrated.\n5. Maximum load sustained before failure is recorded.", 2, 5, "April 16-18", "Civil Dept, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Abhishek", "9304927866", "🌉"],
    ["Hydrohack: Aqua-Genesis", 2, "Group", "Dive into the science of clean water! Design and demonstrate functional water treatment models to purify raw, turbid water.", "1. Format: Group competition, 3-hour time limit.\n2. Treat provided raw water to reduce turbidity and colour.\n3. Bring your own working model and materials.\n4. Power supply provided; bring own extension cords.\n5. No modifications after clock begins.\n6. Adhere to safety norms.", 2, 5, "April 16-17", "Civil Dept, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Sanjar Nawaz", "8434540434", "💧"],
    ["Robo War", 2, "Group", "Build a robot to push the opposing robot out of the ring or flip it over. High-stakes arena combat, one-on-one!", "1. Weight: Max 50 KG (excluding controls/wires).\n2. Control: Remote-controlled or manual (wired).\n3. Power: Electric only, max +24V DC. No IC engines.\n4. Design: Must remain a single centralized unit.", 2, 5, "April 16-17", "Mech Block, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Aryan Mishra", "7319695113", "🤖"],
    ["Mech Nova – 3D", 2, "Group", "Showcase your visionary mechanical engineering ideas through a 3D model or detailed technical poster focused on sustainable breakthroughs!", "1. Format: Live presentations.\n2. Team: 2 to 4 members from the same academic year.\n3. Time: 2-hour setup and evaluation window.\n4. Content must be 100% original.\n5. Qualifier: April 16 | Final: April 17.", 2, 4, "April 16-17", "Mech Block, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Pranav Kumar", "9801165326", "⚙️"],
    ["Model Presentation (Innovate)", 2, "Group", "Present working models or demonstrative prototypes tackling real-world problems in Science, Society, and the Environment!", "1. Format: Group (max 4). One project per student.\n2. Working models or demonstrative prototypes.\n3. Mandatory: Printed abstract (100+ words) and presentation charts.\n4. Charts must include: Block Diagram, Working Principle, Advantages, Disadvantages, Future Scope.\n5. College uniform and ID cards required.", 2, 4, "April 16", "Exhibition Hall, CIT Ranchi", 1000, "₹1,000", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Shivam Prakash", "8434074622", "🔬"],
    ["RapidCad Event", 2, "Solo", "The ultimate test of CAD proficiency, accuracy, and speed. Translate 2D drawings into precise digital models using AutoCAD!", "1. Format: Individual, computer-based CAD competition.\n2. Real-world mechanical component problem statements.\n3. No smartphones or internet access.\n4. Start from scratch – no pre-saved files.\n5. Judges' decision is final.", 1, 1, "April 16-17", "CAD Lab, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Roshan Mahto", "6205837804", "📐"],

    // ====== SPORT EVENTS (category_id = 3) ======
    ["The Genesis Premier League (Cricket)", 3, "Team", "Step up to the crease and smash it out of the park! The Genesis Premier League is the ultimate test of teamwork, strategy, and raw athletic talent.", "1. Format: Hard tennis ball knockout tournament, 6-8 overs per innings.\n2. Squad Size: Max 12 players per team.\n3. Equipment: Organizers provide balls and stumps. Bring own bats.\n4. Footwear: Sports shoes mandatory. No metal spikes.\n5. Punctuality: Report 30 minutes before toss. 10-minute grace period.\n6. Umpires' decisions are final.", 8, 12, "April 13-15", "Sports Ground, CIT Ranchi", 2000, "₹2,000", "1st Prize: ₹15,000 | 2nd Prize: ₹8,000 | Certificates for all!", "Sagar Das", "7079069440", "🏏"],
    ["Court Kings (Basketball)", 3, "Team", "Lace up and hit the hardwood! \"Court Kings\" is where agility, teamwork, and sheer athleticism take center stage.", "1. Format: 5v5 full-court knockout tournament.\n2. Squad: 5 to 12 players.\n3. Match: Four quarters of 8 minutes each.\n4. Footwear: Non-marking basketball shoes mandatory.\n5. Uniforms: Matching numbered jerseys encouraged.\n6. Standard FIBA rules apply.", 5, 12, "April 13-15", "Basketball Court, CIT Ranchi", 1500, "₹1,500", "1st Prize: ₹8,000 | 2nd Prize: ₹5,000 | Certificates for all!", "Gaurav", "8797309609", "🏀"],
    ["Smash Point (Badminton)", 3, "Mixed Doubles", "Grab a partner and own the court! \"Smash Point\" is Genesis's high-octane Mixed Doubles badminton tournament.", "1. Format: Mixed Doubles (players of different genders).\n2. Match: Single set of 21 or 30 points; Semi/Finals best-of-three.\n3. Equipment: Organizers provide shuttlecocks. Bring own racquets.\n4. Footwear: Indoor non-marking shoes mandatory.\n5. Report 15 minutes before scheduled match.", 2, 2, "April 13-15", "Indoor Court, CIT Ranchi", 500, "Solo: ₹500 | Doubles: ₹1,000", "Solo: 1st ₹3,000/2nd ₹2,000 | Doubles: 1st ₹5,000/2nd ₹3,000 | Certificates!", "Aditya Prasad", "6200760863", "🏸"],
    ["Spin & Smash (Table Tennis)", 3, "Solo/Doubles", "Lightning-fast reflexes, vicious backspin, and absolute precision! Open-bracket Table Tennis tournament.", "1. Format: Solo, mixed-gender knockout bracket.\n2. Match: Best-of-3 (prelims), Best-of-5 (semis/finals), 11 points.\n3. Equipment: Organizers provide ITTF 3-Star balls. Bring own bat/paddle.\n4. Indoor non-marking shoes mandatory.\n5. Standard service rules apply. No hidden serves.", 1, 2, "April 13-15", "Indoor Hall, CIT Ranchi", 300, "Solo: ₹300 | Doubles: ₹500", "Solo: 1st ₹3,000/2nd ₹2,000 | Doubles: 1st ₹5,000/2nd ₹3,000 | Certificates!", "Shivam", "9102574169", "🏓"],
    ["The Grandmaster's Gambit (Chess)", 3, "Solo", "Absolute silence. Absolute focus. Genesis's ultimate battle of the minds on 64 squares!", "1. Format: Solo, open-bracket (Knockout or Swiss system).\n2. Time Control: Rapid (10+0); Semi/Finals (15+10).\n3. Equipment provided: boards, pieces, digital clocks.\n4. Touch-Move Rule strictly enforced.\n5. Zero tolerance: All devices must be switched off.\n6. Be at your board when the round begins.", 1, 1, "April 13-15", "Indoor Hall, CIT Ranchi", 500, "₹500", "1st Prize: ₹5,000 | 2nd Prize: ₹3,000 | Certificates for all!", "Mohit Gupta", "6204740718", "♟️"],

    // ====== FUN & ADVENTURE EVENTS (category_id = 4) ======
    ["Graffiti (Wall Painting)", 4, "Solo/Duo", "Leave your mark on Genesis! Transform blank college walls into vibrant, thought-provoking masterpieces with your street art skills!", "1. Format: Solo or Duo (max 2).\n2. Designated 5x5 feet wall space provided.\n3. Pre-Approval: Upload rough sketch during registration.\n4. Time Limit: Exactly 3 hours.\n5. Bring own paints, spray cans, markers, brushes.\n6. Keep surrounding areas clean.\n7. Art must be appropriate for college environment.", 1, 2, "April 16-17", "Campus Walls, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | Certificates for all!", "Sneha Verma", "9142825037", "🎨"],
    ["The Director's Cut (Short Film)", 4, "Group", "Quiet on set, and action! Tell compelling stories and showcase your cinematic flair through short films or Instagram Reels!", "1. Format: Group (2-6 members).\n2. Short Film: 3-10 minutes. Reel: 30-90 seconds (vertical 9:16).\n3. Submit Google Drive or YouTube link.\n4. Footage must be originally shot by the team.\n5. Use royalty-free music recommended.\n6. No explicit content, violence, or profanity.", 2, 6, "April 16-18", "Screening Room, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | Certificates for all!", "Amit Paul", "9113300165", "🎬"],
    ["The Cryptic Trail (Treasure Hunt)", 4, "Solo/Duo", "Think you know every corner of CIT? Hidden clues, ciphers, and riddles across campus lead to the ultimate prize!", "1. Format: Solo or team of 2.\n2. Series of interconnected riddles; solve one to find the next.\n3. All clues within official campus boundaries.\n4. Time Limit: Exactly 2 hours.\n5. No destroying, hiding, or moving clues.\n6. Smartphones allowed for research; no external help.", 1, 2, "April 16-17", "Entire Campus, CIT Ranchi", 500, "₹500", "1st Prize: ₹8,000 | Certificates for all!", "Abhishek Ramani", "8210445841", "🗺️"],
    ["Roadies CIT", 4, "Solo", "Do you have what it takes to survive the ultimate test of endurance? Multiple intense rounds testing strength, stamina, and problem-solving!", "1. Format: Solo registration. May be grouped into impromptu teams.\n2. Follow all safety instructions from taskmasters.\n3. Dress Code: Sportswear and athletic shoes mandatory.\n4. No unfair means or external help.\n5. First-aid station provided on-site.\n6. Judges' decisions are final.", 1, 1, "April 16-17", "Sports Ground, CIT Ranchi", 500, "₹500", "1st Prize: ₹10,000 | Certificates for all!", "Pankaj Kumar", "9801003402", "🏋️"],
    ["Free Fire (Booyah Battlegrounds)", 4, "Squad", "The safe zone is shrinking! Prove your squad's dominance in Genesis's official Free Fire tournament!", "1. Format: Classic Battle Royale (Bermuda/Purgatory/Kalahari).\n2. Account: Must be ranked Diamond or above.\n3. Registration secures one team slot.\n4. Mobile phones only – no emulators.\n5. Anti-Cheat: Zero tolerance for hacks/third-party software.\n6. Custom Room ID shared 15 min before match.\n7. Must use registered IGN and Player ID.", 1, 4, "April 16-17", "Online (Custom Room)", 800, "₹800", "1st Prize: ₹15,000 | Highest Killer: ₹5,000 | Certificates for all!", "Sagar Verma", "9771119515", "🔥"],
    ["BGMI (Genesis Royale)", 4, "Squad", "Drop in, loot up, and survive. The ultimate BGMI battleground with intense custom room lobbies!", "1. Format: Classic Battle Royale (Erangel/Miramar/Sanhok).\n2. Account: Must be ranked Platinum or above.\n3. Registration secures one team slot.\n4. Mobile phones only – no emulators, iPads, or tablets.\n5. Anti-Cheat: Zero tolerance.\n6. Custom Room ID shared 15 min before match.\n7. Must use registered IGN and Character ID.", 1, 4, "April 16-17", "Online (Custom Room)", 1000, "₹1,000", "1st Prize: ₹20,000 | Highest Killer: ₹5,000 | Certificates for all!", "Aamir", "6299931711", "🎮"]
  ];

  events.forEach(e => db.run(insertSQL, e));

  saveDb(db);
  console.log(`✅ Seeded ${events.length} events across ${categories.length} categories`);
}

seedDatabase();
